local opts = { noremap = true, silent = true }  -- 通用映射选项：无递归、静默执行
vim.keymap.set('i', '<c-space>', 'coc#refresh()', { expr = true, silent = true })
vim.keymap.set('i', '<Tab>', 'pumvisible() ? "\\<C-n>" : "\\<Tab>"', { expr = true, silent = true })
vim.keymap.set('i', '<S-Tab>', 'pumvisible() ? "\\<C-p>" : "\\<S-Tab>"', { expr = true, silent = true })
vim.keymap.set('i', '<CR>', 'pumvisible() ? coc#_select_confirm() : "\\<CR>"', { expr = true, silent = true })
vim.keymap.set('n', 'gd', '<Plug>(coc-definition)', opts)
vim.keymap.set('i', '(', '()<Left>', opts)
vim.keymap.set('i', '[', '[]<Left>', opts)
vim.keymap.set('i', '{', '{}<Left>', opts)
vim.keymap.set('i', "'", "''<Left>", opts)
vim.keymap.set('i', '"', '""<Left>', opts)
vim.keymap.set('n','<C-g>',':!gcc main.c -o main&&./main<CR>',opts)
vim.keymap.set('n','<C-t>',':!node index.js<CR>',opts)
vim.keymap.set('n', '<C-r>', ':!cargo run<CR>', opts)
vim.keymap.set('n', '<C-p>', ':!uv run main.py<CR>', opts)
vim.keymap.set('n', '<C-n>', ':NvimTreeToggle<CR>', opts)
vim.keymap.set('n', '<C-m>', ':NvimTreeClose<CR>', opts)
vim.keymap.set('n', '<S-j>', ':BufferLineCyclePrev<CR>', opts)
vim.keymap.set('n', '<S-k>', ':BufferLineCycleNext<CR>', opts)
vim.keymap.set('n', '<C-s>',':BufferLinePickClose<CR>',opts)
vim.keymap.set('n', '<C-h>', ':!node main.ts<CR>',opts)
local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = 'Telescope find files' })
vim.keymap.set('n', '<leader>fg', builtin.live_grep, { desc = 'Telescope live grep' })
vim.keymap.set('n', '<leader>fb', builtin.buffers, { desc = 'Telescope buffers' })
vim.keymap.set('n', '<leader>fh', builtin.help_tags, { desc = 'Telescope help tags' })
