(tool-bar-mode 0)
(global-font-lock-mode t)
(menu-bar-mode 0)
(setq inhibit-startup-message t)
(setq initial-buffer-choice "~/")
(global-display-line-numbers-mode)
(electric-pair-mode 1)
(setq package-archives '(("gnu"    . "https://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")
                         ("nongnu" . "https://mirrors.tuna.tsinghua.edu.cn/elpa/nongnu/")
                         ("melpa"  . "https://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")))
(setq make-backup-files nil)
(setq auto-save-default nil)
(scroll-bar-mode -1)
(icomplete-mode 1)
(global-company-mode 1)
(setq company-idle-delay 0)
(set-frame-font "Iosevka-19")
(require 'emms-setup)
(emms-all)
(setq emms-player-list '(emms-player-mpv))
(setq emms-source-file-default-directory "~/Music/")
(use-package eglot
  :hook ((c-mode c++-mode rust-mode typescript-mode cmake-mode) . eglot-ensure)
)
(add-to-list 'default-frame-alist '(undecorated . t))
(add-hook 'c-mode-common-hook (lambda () (setq c-basic-offset 4)))
(setq flymake-show-diagnostics-at-end-of-line t)
