(tool-bar-mode 0)
(menu-bar-mode 0)
(setq inhibit-startup-message t)
(setq initial-buffer-choice "~/")
(global-display-line-numbers-mode)
(electric-pair-mode 1)
(setq make-backup-files nil)
(setq auto-save-default nil)
(scroll-bar-mode -1)
(icomplete-mode 1)
(set-face-attribute 'default nil :font (font-spec :family "Iosevka" :size 23))
(require 'package)
(setq package-archives '(("gnu" . "https://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")
                         ("nongnu" . "https://mirrors.tuna.tsinghua.edu.cn/elpa/nongnu/")
                         ("melpa" . "https://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")))
(package-initialize)
(add-to-list 'default-frame-alist '(undecorated . t))
(add-hook 'c-mode-common-hook (lambda () (setq c-basic-offset 4)))
