(defun run-c-code()
  (interactive)
  (compile "cd ..;cmake -B build&&cmake --build build&&./build/main"))
(defun run-typescript()
  (interactive)
  (compile "tsc main.ts &&node main.js"))
(global-set-key (kbd "C-c C-g")'run-c-code)
(global-set-key (kbd "C-w")'eval-buffer)
(global-set-key (kbd "C-c C-t")'run-typescript)
