;; -*- lexical-binding: t; -*-
(defun run-typescript()
  (interactive)
  (compile "bun run index.ts"))
(defun python-run()
  (interactive)
  (compile "uv run py"))
(global-set-key (kbd "C-c C-g")'run-c-code)
(global-set-key (kbd "C-c C-t")'run-typescript)
(provide 'keybind)
(defun make-files()
  (interactive)
  (compile "cd ../;make run clean"))
(global-set-key (kbd "C-c C-g")'make-files)
