[main]
font=JetBrains mono:size=11
dpi-aware=true
letter-spacing=0
include=/home/poss/.config/foot/vscode.ini
#include=/usr/share/foot/themes/alacritty
[key-bindings]
scrollback-up-half-page=Shift+Up
scrollback-down-half-page=Shift+Down
[colors]
alpha=1
[cursor]
blink=yes
